name: Build Docker image
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches:
      - main
jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Set docker tags
        id: meta
        uses: docker/metadata-action@v4.1.1
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: spazzy757/licences
          tags: |
            type=sha,format=long,prefix=,priority=200
            type=raw,value=latest,enable={{is_default_branch}},priority=100
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
